### ISSUE TITLE
Upgrade Required: npm WARN deprecated tough-cookie@2.2.2

### ISSUE THREAD

**Issue by mgifford** [pa11y/webservice-client-node#6]
$ npm install pa11y-webservice-client-node

npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
chalk@1.1.3 node_modules/chalk -> node_modules/har-validator/node_modules/chalk
pa11y-webservice@2.0.1 /Users/mikegifford/pa11y-webservice
├─┬ jscs@2.11.0
│ ├─┬ babel-jscs@2.0.5
│ │ └─┬ babel-core@5.8.38
│ │   └── chalk@1.1.3 
│ └── chalk@1.1.3 
├─┬ pa11y@4.0.1
│ └── chalk@1.1.3 
├── pa11y-webservice-client-node@1.2.0  extraneous
└─┬ request@2.74.0
  └─┬ har-validator@2.0.6
    └── chalk@1.1.3

**Comment by joseluisbolos** [comment]
Thanks a lot for your report, @mgifford 

I've just published [version 1.2.1](https://github.com/pa11y/webservice-client-node/releases/tag/1.2.1) which fixes this issue.
